version: '3'

services:
  app:
    container_name: semantive-challange
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/semantive_challange
    ports:
      - "8000:8000"
