# Generated by Django 2.1.3 on 2018-12-09 19:14

from django.db import migrations, models
import django.db.models.deletion
import djangoapp.apps.pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('text_content', models.TextField(null=True)),
                ('images_in_progress', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=djangoapp.apps.pages.models.get_image_path)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.PageTask')),
            ],
        ),
    ]
